# Generated by Django 5.0.3 on 2024-07-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
